name: Nightly Releases

on:
  push:
    branches: [ dev, ci/nightlies ]

jobs:

  docs:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2

        - name: install ninja
          run: sudo apt update && sudo apt install ninja-build

        - name: install python dependencies
          run: pip3 install pyyaml docutils jinja2
          
        - name: make build directory
          run: mkdir -p build

        - name: clone latest flucoma-core 
          run: git clone --branch dev https://github.com/flucoma/flucoma-core.git core

        - name: clone latest flucoma-docs
          run: git clone --branch dev https://github.com/flucoma/flucoma-docs.git docs
        
        - name: cmake
          run: cmake -GNinja -DFLUID_PATH=../core -DDOCS=ON -DFLUID_DOCS_PATH=../docs ..
          working-directory: build
          
        - name: install
          run: ninja MAKE_PD_REF
          working-directory: build

        - uses: actions/upload-artifact@v2
          with:
            name: docs
            path: build/pd_ref

  macbuild:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: install ninja
        run: brew install ninja

      - name: get pd source
        run: git clone https://github.com/pure-data/pure-data.git sdk
        
      - name: make build directory
        run: mkdir -p build

      - name: clone latest flucoma-core
        run: git clone --branch dev https://github.com/flucoma/flucoma-core.git core   
        
      - name: cmake
        run: cmake -GNinja -DPD_PATH=../sdk -DFLUID_PATH=../core ..
        working-directory: build
        
      - name: install
        run: ninja install
        working-directory: build

      - uses: actions/upload-artifact@v2                                                                                                                                                 
        with:                                                                                                                                                                            
          name: macbuild                                                                                                                                                                 
          path: release-packaging/FluidCorpusManipulation

  winbuild:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: get pd binaries
        run : Invoke-WebRequest -Uri https://msp.puredata.info/Software/pd-0.51-4.msw.zip -OutFile sdk.zip

      - name: unzip pd binaries
        run: Expand-Archive sdk.zip -DestinationPath ./ -Force
        
      - name: make build directory
        run: mkdir -p build

      - name: clone latest flucoma-core
        run: git clone --branch dev https://github.com/flucoma/flucoma-core.git core   
        
      - name: cmake
        run: cmake -DPD_PATH="../pd-0.51-4" -DFLUID_PATH="../core" ..
        working-directory: build
        
      - name: install
        run: cmake --build . --target install --config Release
        working-directory: build

      - uses: actions/upload-artifact@v2                                                                                                                                                 
        with:                                                                                                                                                                            
          name: winbuild                                                                                                                                                                
          path: "release-packaging/FluidCorpusManipulation"

  linuxbuild:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: install ninja 
        run: sudo apt update && sudo apt install ninja-build

      - name: get pd source
        run: git clone https://github.com/pure-data/pure-data.git sdk
        
      - name: make build directory
        run: mkdir -p build

      - name: clone latest flucoma-core
        run: git clone --branch dev https://github.com/flucoma/flucoma-core.git core
        
      - name: cmake
        run: cmake -GNinja -DPD_PATH=../sdk -DFLUID_PATH=../core ..
        working-directory: build
        
      - name: install
        run: ninja install
        working-directory: build

      - uses: actions/upload-artifact@v2                                                                                                                                                 
        with:                                                                                                                                                                            
          name: linuxbuild                                                                                                                                                                
          path: release-packaging/FluidCorpusManipulation
  
  release:
    runs-on: ubuntu-latest
    needs: [macbuild, winbuild, linuxbuild, docs]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs

      #### LINUX ####
      - uses: actions/download-artifact@v2
        with:
          name: linuxbuild
          path: linux
      
      - name: copy docs to linux
        run: cp -r docs linux

      - name: compress linux
        run: zip -r ../FluCoMa-PD-Linux-nightly.zip .
        working-directory: linux

      #### MAC ####
      - uses: actions/download-artifact@v2
        with:
          name: macbuild
          path: mac

      - name: copy docs to mac
        run: cp -r docs mac

      - name: compress mac
        run: zip -r ../FluCoMa-PD-Mac-nightly.zip .
        working-directory: mac

      #### WINDOWS ####
      - uses: actions/download-artifact@v2
        with:
          name: winbuild
          path: win

      - name: copy docs to windows
        run: cp -r docs win

      - name: compress windows
        run: zip -r ../FluCoMa-CLI-Windows-nightly.zip .
        working-directory: win
      
      #### UPLOAD RELEASE ####
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: package and upload
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: FluCoMa PureData Nightly Build
          prerelease: true
          body: "This is a nightly build of the FluCoMa PureData package. As such, be warned there may be bugs or other unexpected behaviour. The build hash is ${{ github.sha }}"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: FluCoMa-PD-*.zip
          file_glob: true
          tag: nightly
          overwrite: true
