name: Nightly Releases

on:
  push:
    branches: [ dev, ci/nightlies ]

jobs:
  # Eventually this https://github.community/t/create-matrix-with-multiple-os-and-env-for-each-one/16895/5
  macbuild:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: get pd source
        run: git clone https://github.com/pure-data/pure-data.git sdk
        
      - name: make build directory
        run: mkdir -p build
        
      - name: cmake
        run: cmake -DPD_PATH=../sdk ..
        working-directory: build
        
      - name: install
        run: make install -j$(sysctl -n hw.ncpu)
        working-directory: build

      - name: zip release
        run: zip -r ../FluCoMa-PD-Mac-nightly.zip FluidCorpusManipulation
        working-directory: release-packaging

      - uses: actions/upload-artifact@v2                                                                                                                                                 
        with:                                                                                                                                                                            
          name: macbuild                                                                                                                                                                 
          path: FluCoMa-PD-Mac-nightly.zip

  winbuild:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: get pd binaries
        run : Invoke-WebRequest -Uri https://msp.puredata.info/Software/pd-0.51-4.msw.zip -OutFile sdk.zip

      - name: unzip pd binaries
        run: Expand-Archive sdk.zip -DestinationPath ./ -Force

      - name: ls
        
      - name: make build directory
        run: mkdir -p build
        
      - name: cmake
        run: cmake -DPD_PATH="../sdk" ..
        working-directory: build
        
      - name: install
        run: cmake --build . --target install
        working-directory: build

      - name: remove pdb files
        run: Remove-Item install -Recurse -Include *.pdb

      - name: zip release
        run: Compress-Archive release-packaging/FluidCorpusManipulation FluCoMa-PD-Windows-nightly.zip

      - uses: actions/upload-artifact@v2                                                                                                                                                 
        with:                                                                                                                                                                            
          name: winbuild                                                                                                                                                                
          path: FluCoMa-PD-Windows-nightly.zip

  linuxbuild:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: get pd source
        run: git clone https://github.com/pure-data/pure-data.git sdk
        
      - name: make build directory
        run: mkdir -p build
        
      - name: cmake
        run: cmake -DPD_PATH=../pd-0.51-4 ..
        working-directory: build
        
      - name: install
        run: make install -j$(nproc)
        working-directory: build

      - name: zip release
        run: zip -r ../FluCoMa-PD-Linux-nightly.zip FluidCorpusManipulation
        working-directory: release-packaging

      - uses: actions/upload-artifact@v2                                                                                                                                                 
        with:                                                                                                                                                                            
          name: linuxbuild                                                                                                                                                                
          path: FluCoMa-PD-Linux-nightly.zip
  
  release:
    runs-on: ubuntu-latest
    needs: [macbuild, winbuild, linuxbuild]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: macbuild
          path: .
      
      - uses: actions/download-artifact@v2
        with:
          name: winbuild
          path: .

      - uses: actions/download-artifact@v2
        with:
          name: linuxbuild
          path: .
      
      - name: see
        run: ls -R
        
      - name: package and upload
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: FluCoMa PureData Nightly Build
          prerelease: true
          body: "This is a nightly build of the FluCoMa PureData package. As such, be warned there may be bugs or other unexpected behaviour. The build hash is ${{ github.sha }}"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: FluCoMa-PD-*.zip
          file_glob: true
          tag: 1.0.0-nightly
          overwrite: true
