name: Release
on:
  workflow_dispatch:

jobs:
  macbuild:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: flucoma/actions/env@v5 
      - uses: flucoma/actions/pd@v5
        with:
          branch: origin/main

      - name: compress archive
        run: zip -r FluCoMa-PD-Mac.zip FluidCorpusManipulation
        working-directory: release-packaging

      - uses: actions/upload-artifact@v2
        with:
          name: macbuild
          path: release-packaging/FluCoMa-PD-Mac.zip

  winbuild:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: flucoma/actions/env@v5         
      - uses: flucoma/actions/pd@v5
        with:
          branch: origin/main

      - name: compress archive
        run: 7z a FluCoMa-PD-Windows.zip FluidCorpusManipulation
        working-directory: release-packaging

      - uses: actions/upload-artifact@v2 
        with:
          name: winbuild
          path: release-packaging/FluCoMa-PD-Windows.zip

  linuxbuild:
    runs-on: ubuntu-18.04
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: flucoma/actions/env@v5
      - uses: flucoma/actions/pd@v5
        with:
          branch: origin/main 

      - name: compress archive
        run: tar -zcvf FluCoMa-PD-Linux.tar.gz FluidCorpusManipulation
        working-directory: release-packaging

      - uses: actions/upload-artifact@v2
        with:
          name: linuxbuild 
          path: release-packaging/FluCoMa-PD-Linux.tar.gz
          
      - id: get-version
        run: echo "::set-output name=version::$(cat flucoma.version.rc)"
        working-directory: build/_deps/flucoma-core-src
  
  release:
    runs-on: ubuntu-latest
    needs: [macbuild, winbuild, linuxbuild]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs

      #### LINUX ####
      - uses: actions/download-artifact@v2
        with:
          name: linuxbuild

      #### MAC ####
      - uses: actions/download-artifact@v2
        with:
          name: macbuild

      #### WINDOWS ####
      - uses: actions/download-artifact@v2
        with:
          name: winbuild

      - name: package and upload
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ needs.linuxbuild.outputs.version }}
          body: "This is a release build of the FluCoMa PureData package. The build hash is ${{ github.sha }}"
          files: FluCoMa*
          prerelease: true
          tag_name: ${{ needs.linuxbuild.outputs.version }}
          draft: false
